import { notFound } from "next/navigation";
import { isLocale } from "@/lib/i18n";
import { localizedPageMetadata } from "@/lib/seo";

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }) { const { locale } = await params; if (!isLocale(locale)) return {}; return localizedPageMetadata(locale, "/privacy", { ru: "Политика конфиденциальности сайта", kz: "Сайттың құпиялық саясаты" }, { ru: "Как форма записи обрабатывает персональные данные локально.", kz: "Жазылу формасының жеке деректерді жергілікті өңдеуі туралы." }); }
export default async function PrivacyPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params; if (!isLocale(locale)) notFound(); const isRu = locale === "ru";
  return <article className="legal-page"><p className="eyebrow">{isRu ? "Политика данных" : "Деректер саясаты"}</p><h1>{isRu ? "Конфиденциальность" : "Құпиялық"}</h1><p className="lede">{isRu ? "Эта версия сайта не отправляет и не сохраняет персональные данные формы записи." : "Сайттың бұл нұсқасы жазылу формасының жеке деректерін жібермейді және сақтамайды."}</p><h2>{isRu ? "Что работает сейчас" : "Қазір не жұмыс істейді"}</h2><p>{isRu ? "Имя, телефон и комментарий находятся только в оперативной памяти страницы во время сценария. После просмотра результата поля очищаются. В localStorage сохраняется только выбранный язык." : "Аты-жөні, телефон және пікір сценарий кезінде тек беттің жедел жадында болады. Нәтижені көргеннен кейін өрістер өшіріледі. localStorage ішінде тек таңдалған тіл сақталады."}</p><h2>{isRu ? "Что не подключено" : "Не қосылмаған"}</h2><p>{isRu ? "Нет базы данных, аналитики формы, CRM, оплаты, авторизации, WhatsApp Business API, реального расписания, напоминаний или автоматической отправки." : "Дерекқор, форма аналитикасы, CRM, төлем, авторизация, WhatsApp Business API, нақты кесте, еске салу немесе автоматты жіберу жоқ."}</p><h2>{isRu ? "Внешние ссылки" : "Сыртқы сілтемелер"}</h2><p>{isRu ? "Отдельные кнопки телефона, WhatsApp, Instagram и 2ГИС ведут на внешние сервисы, где действуют их собственные правила." : "Телефон, WhatsApp, Instagram және 2GIS батырмалары өз ережелері бар сыртқы сервистерге апарады."}</p></article>;
}
